### PR TITLE
Build many gen

### PR DESCRIPTION
**Pull request by fvlima**
Change `Model.build_many` to return a generator instead list, as commented here https://github.com/lamenezes/simple-model/issues/15

All tests are ok

### CODE REVIEW

**Comment by fvlima** [comment]
There is a problem with mypy when a method do `yield from ()`, as seen here https://github.com/python/mypy/issues/4444

**Comment by fvlima** [comment]
I did another tests increasing the amount of data to 60 thousand records and change the method build_many to use generator internally to verify the key sets. The total time and mainly the memory were reduced a little bit more

**Comment by lamenezes** [comment]
Thanks for the PR @fvlima! I'm going perform some local tests on the code you submitted and then I return to you.

**Comment by fvlima** [comment]
As commented here [1], this PR will not be used, and other change will be made to allow build many and retrieve a generator by default instead a list.

1 - https://github.com/lamenezes/simple-model/issues/15

**Pull request closed without merging**
